// <auto-generated />
using System;
using AlbionLootBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbionLootBot.Migrations
{
    [DbContext(typeof(LootBotDbContext))]
    [Migration("20261007222823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("AlbionLootBot.Models.CalculationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ItemTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LootsplitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NetTotalAfterTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerPersonGrossShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerPersonNetShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Remainder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SilverBagTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRatePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId")
                        .IsUnique();

                    b.HasIndex("LootsplitId");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("AlbionLootBot.Models.LootItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LootsplitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxableEntity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("ValueSilver")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LootsplitId");

                    b.ToTable("LootEntity");
                });

            modelBuilder.Entity("AlbionLootBot.Models.Lootsplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.ToTable("LootSplit");
                });

            modelBuilder.Entity("AlbionLootBot.Models.LootsplitParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LootsplitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LootsplitId", "PlayerId")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("AlbionLootBot.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordPlayerId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AlbionLootBot.Models.CalculationEntity", b =>
                {
                    b.HasOne("AlbionLootBot.Models.Lootsplit", "Lootsplit")
                        .WithMany()
                        .HasForeignKey("LootsplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lootsplit");
                });

            modelBuilder.Entity("AlbionLootBot.Models.LootItem", b =>
                {
                    b.HasOne("AlbionLootBot.Models.Lootsplit", "Lootsplit")
                        .WithMany("Items")
                        .HasForeignKey("LootsplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lootsplit");
                });

            modelBuilder.Entity("AlbionLootBot.Models.LootsplitParticipant", b =>
                {
                    b.HasOne("AlbionLootBot.Models.Lootsplit", "Lootsplit")
                        .WithMany("Participants")
                        .HasForeignKey("LootsplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlbionLootBot.Models.Player", "Player")
                        .WithMany("Participations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lootsplit");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AlbionLootBot.Models.Lootsplit", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AlbionLootBot.Models.Player", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
